language: node_js
sudo: false
node_js:
- '8'
cache:
  directories:
  - node_modules
env:
- CXX=g++-4.8
before_install:
- export TZ=Asia/Shanghai
addons:
  ssh_known_hosts: github.com
script:
- npm run build
deploy:
  provider: script
  script: .travis/deploy.sh
  skip_cleanup: true
  on:
    branch: master
