language: node_js

sudo: false

node_js:
  - "14"

cache:
  yarn: true
  directories:
    - node_modules

branches:
  only:
    - master

before_install:
  - export TZ=Asia/Shanghai

script:
  - git clone -b master https://github.com/yangyang0507/yangyang0507.github.io.git ./.deploy_git

after_success:
  - yarn run deploy
